### ISSUE TITLE
dsb does not run when intersection is False

### ISSUE THREAD

**Issue by JHYSiu** [DendrouLab/panpipes#1]
dsb does not run when half the samples are rna + adt, half the samples are rna only (and no intersection between rna,adt is taken). 

fix is to take the intersection of the background:  mu.pp.intersect_obs(mdata_bg) prior to mu.prot.pp.dsb

**Comment by wlason** [comment]
I ran into the same problem in panpipes v0.4.1 and the solution given by @JHYSiu solves the issue.

**Comment by wlason** [comment]
This is still not fixed as of today @bio-la and I run into the same problem again with another dataset. I will write a fix and create a PR.

**Comment by deevdevil88** [comment]
@wlason  you just need to add an if statement in the preprocess peot script, that when intersect ,`rna,prot` is not set, to take the intersect of BG and unfilt mdata and then run sab.
