### ISSUE TITLE
ingest config won't work unless igraph updated

### ISSUE THREAD

**Issue by JHYSiu** [DendrouLab/panpipes#101]
did conda install...had igraph 0.10.2. When I tried to do ingest config, had following error: AttributeError: module 'igraph' has no attribute 'VertexClustering'

Solution: uninstall igraph, pip re-installed igraph-0.10.8. Worked.

**Comment by bio-la** [comment]
Hi @JHYSiu thanks for reporting your issue.
I am unsure why your environment had an outdated version of igraph. my guess is that by installing other dependencies in the same environment something might have caused the downgrading of `igraph` to `0.10.2`

 I have two working panpipes environment where I have `igraph ==0.10.5`

for sanity check i just replicated in a fresh environment the installation we provide on the installation guidelines and it fetches
```
igraph==0.10.8
python-igraph==0.10.8
```

`panpipes ingestion config` doesn't produce the error you reported with any of the two versions of igraph.

If you don't have further comments I will close this issue but we may consider fixing the version of igraph in a future `panpipes` release.
thanks for using `panpipes`!
