### ISSUE TITLE
Documentation mentions non-existent `integration plot_pcas` task

### ISSUE THREAD

**Issue by wlason** [DendrouLab/panpipes#117]
Documentation of integration step [here](https://panpipes-pipelines.readthedocs.io/en/latest/workflows/integration.html) in step 2 mentions `panpipes integration plot_pcas` task, which doesn't exist in `pipeline_integration.py`. The PCA plots are already produced at `panpipes preprocess` stage.

![image](https://github.com/DendrouLab/panpipes/assets/40389067/40ae6227-8a64-4880-80ba-8bea28bccb18)

**Comment by crichgriffin** [comment]
Thanks! this is old copy pasta. I will fix it.
