### ISSUE TITLE
Protein PCA fails when number of samples > number of features

### ISSUE THREAD

**Issue by wlason** [DendrouLab/panpipes#120]
In case of small number of samples and when number of features is 50, `panpipes preprocess` incorrectly establishes the number of PCAs that should be calculated: 

https://github.com/DendrouLab/panpipes/blob/035c91cb3725621f127025982c9453b8f2558819/panpipes/python_scripts/run_preprocess_prot.py#L232

Changing this line to `n_comps=min(50,all_mdata['prot'].var.shape[0]-1, all_mdata['prot'].var.shape[1]-1)` fixes the issue.

I also suggest considering changing the solver to `auto` below a certain threshold of cells, as it's more robust (but slower).

**Comment by bio-la** [comment]
thanks for spotting this issue @wlason. can you open a branch with your suggested modification and open a PR? in this way i can review your code. thank you!

**Comment by bio-la** [comment]
hey @wlason we have been looking at this and i don't see why using the number of columns of the .var slot would actually be a fix? 
the idea behind running PCA is that you end up with N components that are less than number of Features. 
in the code above, `min(50,all_mdata['prot'].var.shape[0]-1)` ensures that N is at least 50 when you have more than 50 features, or  number of features minus 1. (the rows of the `.var` slot minus 1)

however we're curious what error did you observe? can you post the log file please?
thank you!
