### ISSUE TITLE
'TypeError: _init_from_dict_() got an unexpected keyword argument 'matrix'

### ISSUE THREAD

**Issue by Yohana-Berhe** [DendrouLab/panpipes#125]
I am using panpipes to analyze CITEseq data, and managed to run the ingest workflow and get the resulting h5mu file. However, when I try to load the resulting 'x_unfilt.h5mu' file in a jupyter notebook using 'muon.read_h5mu()', I get an error that says: ' 'TypeError: _init_from_dict_() got an unexpected keyword argument 'matrix'.

**Comment by bio-la** [comment]
Hi @Yohana-Berhe i can't replicate your issue with the environment you provided in issue #126.  
have you checked if the mudata is not corrupted? thanks!
