### ISSUE TITLE
documentation ingestion 

### ISSUE THREAD

**Issue by bio-la** [DendrouLab/panpipes#153]
Hi @Lilly-May thanks for helping with the documentation!
please start here:
- create a pipeline_ingestion_yaml.md page with the full pipeline.yml text 
- add an explanation to each argument of the file. (what setting to True/False indicates, what are the options, etc.)
- please add  links to the existing documentation pages where needed, and feel free to reduce the size of the pipeline.yml to a minimum
 for example:

https://github.com/DendrouLab/panpipes/blob/4d94536a025fc0c16a065fb073307a728aacb44c/panpipes/panpipes/pipeline_ingest/pipeline.yml#L159

all the explanations in the yml file could be trimmed down consistently in the yml and be used in the documentation page instead.

**Comment by Lilly-May** [comment]
This issue was closed with PR #158.
