### ISSUE TITLE
scvi version 

### ISSUE THREAD

**Issue by SarahOuologuem** [DendrouLab/panpipes#156]
The latest version of scvi-tools `1.0.4` works for scVI and totalVI but causes errors and warnings when running multiVI: https://discourse.scverse.org/t/error-when-training-model-on-m3-max-mps/1896 
Version `0.20.3` is stable and works for scVI, totalVI, and multiVI. 

Our solution is to have two installation versions: `stable` and `latest`.

**Comment by bio-la** [comment]
let's test scvi 1.1.0 
https://github.com/theislab/scvelo/issues/1186
