### ISSUE TITLE
Installation instructions macOS Silicon

### ISSUE THREAD

**Issue by Lilly-May** [DendrouLab/panpipes#157]
Add a section to the installation instructions that is specific to macOS Silicon. [scvi-tools](https://docs.scvi-tools.org/en/latest/installation.html) can only run on macOS machines with M-chips when installed via a native Python version. The documentation should include a step-by-step explanation of how to achieve this.

**Comment by bio-la** [comment]
Hi @Lilly-May, is this in the documentation yet? thanks!
