### ISSUE TITLE
adding actions to follow each tutorial

### ISSUE THREAD

**Issue by bio-la** [DendrouLab/panpipes#172]
@kevinrue as discussed these are the actions to implement 

multimodal single cell
- [x] CI for anndata ingestion tutorial https://panpipes-tutorials.readthedocs.io/en/latest/ingesting_data/Ingesting_data_with_panpipes.html
- [ ] CI for raw multiome ingestion https://panpipes-tutorials.readthedocs.io/en/latest/ingesting_multiome/ingesting_mome.html
- [x] CI for preprocessing https://panpipes-tutorials.readthedocs.io/en/latest/filtering_data/filtering_data_with_panpipes.html
- [x] CI for integration https://panpipes-tutorials.readthedocs.io/en/latest/uni_multi_integration/Integrating_data_with_panpipes.html
- [ ] CI for mouse gene score https://panpipes-tutorials.readthedocs.io/en/latest/ingesting_mouse/Ingesting_mouse_data_with_panpipes.html
- [ ] CI for clustering https://panpipes-tutorials.readthedocs.io/en/latest/clustering/clustering_tutorial.html
- [ ] CI for refmap https://panpipes-tutorials.readthedocs.io/en/latest/refmap_pancreas/Reference_mapping.html
- [ ] CI for viz https://panpipes-pipelines.readthedocs.io/en/latest/tutorials/index.html#:~:text=Visualization%20workflow

SPATIAL: 
- [x] SPATIAL ingestion CI https://panpipes-pipelines.readthedocs.io/en/latest/tutorials/index.html#:~:text=Ingesting%2010X%20Visium%20data
- [x] SPATIAL preprocess CI https://panpipes-tutorials.readthedocs.io/en/latest/preprocess_spatial_data/preprocess_spatial_data_with_panpipes.html
- [x] SPATIAL deconvolution CI https://panpipes-pipelines.readthedocs.io/en/latest/tutorials/index.html#:~:text=Deconvoluting%20spatial%20data

**Comment by SarahOuologuem** [comment]
Small note: I still need to update the yaml file of the spatial deconvolution tutorial to the latest changes. Will let you know when this is done!
