### ISSUE TITLE
Don't specify transitive dependencies and move development dependencies into a development section

### ISSUE THREAD

**Issue by Zethson** [DendrouLab/panpipes#191]
You don't need to specify transitive dependencies -> anndata, jax etc are already included in e.g. scvi-tools. Only if you need to pin them.

Moreover, dependencies such as pytest are not runtime dependencies and should be moved into a dev section.

**Comment by bio-la** [comment]
@Lilly-May can you look into this? ideally we should be all good with jax and anndata as @Zethson said so we should be removing them from the .toml (we can easily check if something fails with the implemented actions)

**Comment by Zethson** [comment]
I can do it myself @bio-la. Not to say that @Lilly-May couldn't, but I might be faster. Give me a few minutes :)

**Comment by bio-la** [comment]
@Zethson seems we have to put jax explicitly back, can you fix it? i wonder if this is also helping with cell2location import issue that @SarahOuologuem found with `scvi 1.1.1`
https://github.com/scverse/scvi-tools/issues/2582

thanks!

**Comment by Zethson** [comment]
Not sure whether this will fix the issue because it's about the order of dependencies being installed and CUDA being available etc. I mean we can try
