### ISSUE TITLE
filtering pipeline fails with error related to scanpy/preprocessing/_pca.py

### ISSUE THREAD

**Issue by kevinrue** [DendrouLab/panpipes#193]
https://github.com/DendrouLab/panpipes/actions/runs/8006360043/job/21867908763?pr=188#step:14:395

```
ValueError: svd_solver: {svd_solver} can not be used with sparse input. \
#                                   Use "arpack" (the default) or "lobpcg" instead. \
```

Not sure what's going on there :)

**Comment by bio-la** [comment]
good that this worked! we wouldn't have known otherwise that scanpy changed the default from `auto` to `arpack`
https://github.com/DendrouLab/panpipes-tutorials/pull/38

**Comment by bio-la** [comment]
this is sorted now so i'm closing the issue.
