### ISSUE TITLE
ingest rna QC default does not work for mouse data 

### ISSUE THREAD

**Issue by giuliaelgarcia** [DendrouLab/panpipes#216]
In the ingestion pipeline, the default for RNA QC `score_genes` is "MarkersNeutro" which works for human data but not when running panpipes with mouse data. So the default should be present as a group in the provided mouse and human gene csvs in the repo/tutorials.

**Comment by bio-la** [comment]
thanks @giuliaelgarcia , can you change the default in the documentation and in the pipeline.yml?

- [ ] change default to blank in https://panpipes-pipelines.readthedocs.io/en/latest/yaml_docs/pipeline_ingestion_yml.html#providing-a-gene-list
- [ ] change default in https://github.com/DendrouLab/panpipes/blob/8fdca9e02d2445b125ecebe326397257d469296b/panpipes/panpipes/pipeline_ingest/pipeline.yml#L89
