### ISSUE TITLE
cell_cycle_gene default for human won't work with mouse data 

### ISSUE THREAD

**Issue by giuliaelgarcia** [DendrouLab/panpipes#217]
In ingest panpipe cell cycle action `ccgenes` is set to "default"  which links to a cell_cycle gene list for humans only. This makes it so that the pipeline fails when running with mouse data. 
Thus a new gene list for mouse data must be generated and provided before running. This either has to be explicit (that the user must change the gene list) or implemented in the code so that it automatically generates this mouse translation. 

I have, however,  already generated this mouse list for myself from the human one provided in the tutorials, and am happy to add this to the resources folder for other users!

**Comment by bio-la** [comment]
thank you @giuliaelgarcia good idea! 
please do upload the mouse cc genelist in thesame folder as the human one, 

currently setting `ccgenes` to `default` assumes simultaneously:
1. we deal with human data
2. we trust the provided list

specifying a custom path to any file in the ccgenes allows you to escape both assumptions, 

i.e. if you have a mouse list, you CAN'T set `ccgenes` to default but you **can only specify a path to a file.**
if you add your file, we offer the user the option to use it and you should clarify how to do it in the documentation.


actions:

- [ ] add the file to the repo
- [ ] add info on the gene list page https://panpipes-pipelines.readthedocs.io/en/latest/usage/gene_list_format.html
- [ ] add info on the ingestion https://panpipes-pipelines.readthedocs.io/en/latest/yaml_docs/pipeline_ingestion_yml.html#providing-a-gene-list

**Comment by giuliaelgarcia** [comment]
Additionally, the mitochondrial genes in the mouse_qc_list from the tutorial are not all correct, some genes added are not mt and some are not protein-coding. I will attach a list of mt mouse genes which I used to double check which ones were correct.
[mmus_Gcm38_mito.txt](https://github.com/DendrouLab/panpipes/files/14523006/mmus_Gcm38_mito.txt)
