### ISSUE TITLE
improve logging

### ISSUE THREAD

**Issue by bio-la** [DendrouLab/panpipes#247]
@kevinrue as discussed

- [ ] test a mini ruffus pipeline to test how to send an informative error to stdout 

@SarahOuologuem 

- [x] add numbering to the log files to help understanding the order of the tasks

https://github.com/DendrouLab/panpipes/pull/246

**Comment by kevinrue** [comment]
Work in progress: https://github.com/kevinrue/panpipes-logging

**Comment by kevinrue** [comment]
The minimal pipeline now successfully write log messages from within the task script `script.py` to `pipeline.log`.

The output looks like the second line below, amidst typical `pipeline.log` contents:

```
2024-04-03 09:56:03,865 INFO main execution - waiting for 1 jobs to finish 
2024-04-03 09:57:27,757 INFO log script - script.py logging to file 'logs/test.out'
2024-04-03 09:57:34,190 INFO main execution - {"task": "__main__.run_script", "engine": ...
```

I've commented the useful bits that could be reused to do the same in panpipes.
Any question, let me know!

**Comment by kevinrue** [comment]
Having thought about it more today, this log message should probably be emitted from the pipeline script rather from the task itself.

* it would be issue before the task actually runs, which is safer if the task fails during launch
* the pipeline knows explicitly what the log file path is, while the task may not (it emits to stdout and stderr, as far as it's concerned)
