### ISSUE TITLE
Documentation: does not mention how only run no correction for rna and prot in integration 

### ISSUE THREAD

**Issue by giuliaelgarcia** [DendrouLab/panpipes#264]
Tested integration without any tools for batch correction to get a no_correct object and it works fine. 
Will add this to the integration documentation yaml and the workflow so that it is clear.

**Comment by deevdevil88** [comment]
i can confirm this is the case for running on rna and prot, just tested protein modality on my end and it runs through. @giuliaelgarcia  with add this in the documentation when she ggets a chance
