### ISSUE TITLE
scvi integration not plotting in interactive session on HPC

### ISSUE THREAD

**Issue by JarneBelien** [DendrouLab/panpipes#265]
panpipes `integration` keeps terminating for me at the plotting stage when I run it on an interactive session on a cluster. 
The error is always the same indexerror:
![Schermafbeelding 2024-04-25 085908](https://github.com/DendrouLab/panpipes/assets/133022501/e177ad4a-49fe-45d0-bc3d-d4914df3f09e)

The issue is not dataset-specific as @deevdevil88 was able to run `integration` fine without any issues in her environment.
The issue also does not seem scvi-tools version related as my error is reproducible with both v1.1.2 and v1.1.1.

The rna_scvi.log file shows the model does seem to converge (progress bar goes up to 100%) but no figures are outputted to the 'figures' folder.

**Comment by bio-la** [comment]
Hi @JarneBelien and thanks for using panpipes! 
could you please share the scvi log file? also, we should have a checkpoint to save the model just before that command, could you please share that as well?

from the screenshot it seems you're running an older version of panpipes.
