### ISSUE TITLE
Issue in ingest when merging scrublet results with main concatenated mudata object 

### ISSUE THREAD

**Issue by giuliaelgarcia** [DendrouLab/panpipes#276]
I had to reinstall my panpipes and create a new panpipes conda env and now I receive the following numpy error in ingest, check the [screenshot](https://github.com/DendrouLab/panpipes/assets/33758226/0affce41-22be-4a49-b7a7-16a9aa677419)
 stating it can't find doubletscores anymore and also the dtype category error

**Comment by deevdevil88** [comment]
Clsing issues as fixed with PR #277
