### ISSUE TITLE
Gene name has to be index of adata.var in input adata - add to documentation?

### ISSUE THREAD

**Issue by JarneBelien** [DendrouLab/panpipes#286]
Hi, 

I tried to ingest an adata object pulled from the [CZI CellxGene Census](https://chanzuckerberg.github.io/cellxgene-census/). The CZI adata output does not have the gene/feature name as the index of the adata.var dataframe and this lead to the failure of the ingest workflow. Error message: could not find features.

After setting the 'gene name' as the index of the adata.var dataframe, the error was resolved and I was able to ingest the adata object.

Maybe interesting to add this to the documentation of the [submission file](https://panpipes-pipelines.readthedocs.io/en/latest/usage/setup_for_qc_mm.html)?

Cheers

**Comment by bio-la** [comment]
Hi @JarneBelien thanks for raising this issue! I will add it to the documentation.
