### ISSUE TITLE
Turn off scib if no metrics provided

### ISSUE THREAD

**Issue by wlason** [DendrouLab/panpipes#320]
I noticed scib script runs even if there are no cell type labels provided. I was wondering if we could add `run: False` param in the yaml or add checks in the `pipeline_integration.py` script to not submit unnecessary jobs to the cluster if no reference is provided.

**Comment by deevdevil88** [comment]
I think scob can run in a celltype label or batch specific manner

**Comment by deevdevil88** [comment]
Without celltypenlables it runs based on batch

**Comment by wlason** [comment]
I think `run: True/False` would be useful to prevent crashes - especially on smaller datasets.

**Comment by deevdevil88** [comment]
sure i agree addding a run param is not a bad idea, as users can decide if they want it run at all, but all i was trying to say is without celltype label columns not provided it runs on batch

**Comment by deevdevil88** [comment]
im happy to do this @bio-la @wlason when i work on panpipes related stuff tomorrow. unless you are already doing a PR @wlason

**Comment by wlason** [comment]
Happy for you to do it @deevdevil88 !

**Comment by deevdevil88** [comment]
i have added a PR  #321 to add a `run` parameter for both LISI and scib metrics.
