### ISSUE TITLE
Error Visualization Continuous Variable

### ISSUE THREAD

**Issue by SarahOuologuem** [DendrouLab/panpipes#46]
Hi, 

I ran the visualization part of the pipeline with a muData containing both scRNA- and scATAC- data. (Before the visualization step I ran the QC, Preprocessing, Clustering successfully).
When specifying both categorical & continuous variables for the RNA (not the ATAC, I left the ATAC part empty), 
so f.ex. "rna: 
			- rna:total_counts",
it worked completely fine. But when only wanting to plot categorical variables and leaving the continuous variables empty, errors were thrown and the pipeline stopped. The parameter "continuous_violin" was set to False in both cases. 
The errors included: 
	Error in `mutate()`:
		ℹ In argument: `mod = ifelse(X1 %in% c("rna", "prot", "atac", "rep"),
		  X1, "multimodal")`.
		Caused by error in `X1 %in% c("rna", "prot", "atac", "rep")`:
		! object 'X1' not found
when running: 
	Rscript /home/sarah/anaconda3/envs/pipeline_env/lib/python3.8/site-packages/panpipes/R_scripts/plot_metrics.R         --mtd_object sample1_cell_metadata.tsv         --params_yaml pipeline.yml > logs/plot_metrics.log
	
Do I need to specify the parameters in the pipeline.yml in a specific way so that it works? What do I have to consider when only wanting to plot categorical variables? 

Thanks.

**Comment by crichgriffin** [comment]
Thanks for flagging this. The visualisation pipeline needs a bit of a review anyway.

**Comment by bio-la** [comment]
@SarahOuologuem do you still have this issue?

**Comment by SarahOuologuem** [comment]
@bio-la yes, I just now checked & still have this issue. I created a branch for this & will start working on it!
