### ISSUE TITLE
LSI, scATAC-Seq

### ISSUE THREAD

**Issue by SarahOuologuem** [DendrouLab/panpipes#47]
Hi, 

I noticed that the preprocessing/QC part of the pipeline doesn't provide a plot that could guide the decision on whether to exclude the first LSI component or not. 
The signac package provides a plot of the correlation between the sequencing depth and the components: https://stuartlab.org/signac/reference/depthcor. Including this plot in the pipeline may be a nice extension.

**Comment by bio-la** [comment]
solved in #135
