### ISSUE TITLE
WNN in pipeline_integration.py failing with None

### ISSUE THREAD

**Issue by deevdevil88** [DendrouLab/panpipes#74]
Hi,
when modalities in WNN are set as `None`, the pipeline is erroring. it also fails if you use no_correction instead, but works fine if you use a batch correction method.
<img width="797" alt="Screenshot 2023-08-29 at 15 29 03" src="https://github.com/DendrouLab/panpipes/assets/33758226/3dfa3725-d9d2-4330-a85a-eabfc7b6181b">
<img width="1143" alt="Screenshot 2023-08-29 at 15 28 50" src="https://github.com/DendrouLab/panpipes/assets/33758226/53274fef-e5f7-42dd-863a-aa382be0ef68">

Devika

**Comment by bio-la** [comment]
fix in https://github.com/DendrouLab/panpipes/pull/75
