### ISSUE TITLE
pipepline_clustering.py fails when run on multimodal data

### ISSUE THREAD

**Issue by deevdevil88** [DendrouLab/panpipes#8]
hiya,
the clustering pipeline fails when run on the multimodal dims,  seems like the dictionary hasnt been added to ruffus. Here is a screenshot of the command.

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/33758226/222407005-e357a7ad-4cc9-46c6-9a7a-de740d544bb8.png">

Thanks!
Devika

**Comment by crichgriffin** [comment]
This will be solved in PR #13
