### ISSUE TITLE
Typo in readthedocs (integration)

### ISSUE THREAD

**Issue by JHYSiu** [DendrouLab/panpipes#87]
Typo in step 6 of Steps to run here: https://panpipes-pipelines.readthedocs.io/en/latest/workflows/integration.html

Change `panpipes integration make merge_batch_correction` to `panpipes integration make merge_integration`

**Comment by deevdevil88** [comment]
@JHYSiu  thaks for point out, fixed by this PR[https://github.com/DendrouLab/panpipes/pull/88](url)
