### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by deevdevil88** [DendrouLab/panpipes#93]
hi ,
Currently the documentation here : https://panpipes-pipelines.readthedocs.io/en/latest/workflows/qc.html
says `panpipes ingestion`  and ` panpipes ingestion config` , `panpipes ingestion make full`. We tried running this today and it dint work. it only worked with `panpipes ingest make full`. It would be good to know what is that we want this to be, is the documentaiton wrong, or does the code need to be updated

Devika

**Comment by crichgriffin** [comment]
Oh yeah, my bad. I will fix. Its supposed to be ingest

**Comment by deevdevil88** [comment]
No probs and thank you😊
